/**
 * ******************************************************************************************
 * Copyright (C) 2014 - Food and Agriculture Organization of the United Nations (FAO).
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice,this list
 *       of conditions and the following disclaimer.
 *    2. Redistributions in binary form must reproduce the above copyright notice,this list
 *       of conditions and the following disclaimer in the documentation and/or other
 *       materials provided with the distribution.
 *    3. Neither the name of FAO nor the names of its contributors may be used to endorse or
 *       promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,STRICT LIABILITY,OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * *********************************************************************************************
 */
package org.sola.clients.swing.desktop.workflow;

import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import org.sola.clients.beans.application.ApplicationBean;
import org.sola.clients.beans.application.ApplicationServiceBean;
import org.sola.clients.swing.common.controls.CalendarForm;
import org.sola.clients.swing.common.controls.WatermarkDate;
import org.sola.clients.swing.desktop.source.DocumentsManagementExtPanel;
import org.sola.clients.swing.common.utils.FormattersFactory;

/**
 *
 * @author soladev
 */
public class ApplicationServicePanel extends javax.swing.JPanel {

    ApplicationBean applicationBean;
    boolean readOnly = false;

    /**
     * Creates new form ApplicationServicePanel
     */
    public ApplicationServicePanel() {
        initComponents();
        customisePanel();
    }

    public ApplicationServicePanel(ApplicationBean appBean, ApplicationServiceBean serviceBean,
            boolean readOnly) {
        this.applicationBean = appBean;
        this.applicationServiceBean = serviceBean;
        this.readOnly = readOnly;
        initComponents();
        customisePanel();
    }

    private void customisePanel() {
        txtActionDate.setEnabled(!readOnly);
        txtNotes.setEnabled(!readOnly);
        cbxActionCompleted.setEnabled(!readOnly);
        btnActionDateCalender.setEnabled(!readOnly);
        txtFieldA.setEnabled(!readOnly);
        txtFieldB.setEnabled(!readOnly);
        panelA.setVisible(false);
        panelB.setVisible(false);
    }

    private ApplicationServiceBean createServiceBean() {
        if (this.applicationServiceBean == null) {
            this.applicationServiceBean = new ApplicationServiceBean();
        }
        return this.applicationServiceBean;
    }

    private DocumentsManagementExtPanel createDocumentsPanel() {
        if (documentPanel == null) {
            if (applicationBean != null) {
                documentPanel = new DocumentsManagementExtPanel(
                        applicationBean.getSourceList(), null, !readOnly);
            } else {
                documentPanel = new DocumentsManagementExtPanel();
            }
        }
        return documentPanel;
    }

    private void showCalendar(JFormattedTextField dateField) {
        CalendarForm calendar = new CalendarForm(null, true, dateField);
        calendar.setVisible(true);
    }

    public void setFieldALabel(String label) {
        panelA.setVisible(true);
        lblFieldA.setText(label);
    }

    public void setFieldBLabel(String label) {
        panelB.setVisible(true);
        lblFieldB.setText(label);
    }

    public void setPanelA(JPanel panel) {
        panelA.removeAll();
        panelA.add(panel);
    }

    public void hideActionDate() {
        panelActionDate.setVisible(false);
    }

    public void hideActionCompleted() {
        panelActionCompleted.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The lblActionDate of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        applicationServiceBean = createServiceBean();
        jPanel1 = new javax.swing.JPanel();
        documentPanel = createDocumentsPanel();
        groupPanel1 = new org.sola.clients.swing.ui.GroupPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 21));
        panelTop = new javax.swing.JPanel();
        panelActionDate = new javax.swing.JPanel();
        lblActionDate = new javax.swing.JLabel();
        txtActionDate = new WatermarkDate();
        btnActionDateCalender = new javax.swing.JButton();
        panelActionCompleted = new javax.swing.JPanel();
        lblActionCompleted = new javax.swing.JLabel();
        cbxActionCompleted = new javax.swing.JCheckBox();
        panelA = new javax.swing.JPanel();
        lblFieldA = new javax.swing.JLabel();
        txtFieldA = new javax.swing.JTextField();
        panelB = new javax.swing.JPanel();
        lblFieldB = new javax.swing.JLabel();
        txtFieldB = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lblNotes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/sola/clients/swing/desktop/workflow/Bundle"); // NOI18N
        groupPanel1.setTitleText(bundle.getString("ApplicationServicePanel.groupPanel1.titleText")); // NOI18N

        panelTop.setLayout(new java.awt.GridLayout(1, 4, 12, 0));

        lblActionDate.setText(bundle.getString("ApplicationServicePanel.lblActionDate.text")); // NOI18N

        txtActionDate.setFormatterFactory(FormattersFactory.getInstance().getDateFormatterFactory());

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, applicationServiceBean, org.jdesktop.beansbinding.ELProperty.create("${actionDate}"), txtActionDate, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        btnActionDateCalender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/common/calendar.png"))); // NOI18N
        btnActionDateCalender.setBorder(null);
        btnActionDateCalender.setName("btnActionDateCalender"); // NOI18N
        btnActionDateCalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionDateCalenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActionDateLayout = new javax.swing.GroupLayout(panelActionDate);
        panelActionDate.setLayout(panelActionDateLayout);
        panelActionDateLayout.setHorizontalGroup(
            panelActionDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblActionDate, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addGroup(panelActionDateLayout.createSequentialGroup()
                .addComponent(txtActionDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActionDateCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelActionDateLayout.setVerticalGroup(
            panelActionDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionDateLayout.createSequentialGroup()
                .addComponent(lblActionDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActionDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtActionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActionDateCalender))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTop.add(panelActionDate);

        lblActionCompleted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActionCompleted.setText(bundle.getString("ApplicationServicePanel.lblActionCompleted.text")); // NOI18N

        cbxActionCompleted.setText(bundle.getString("ApplicationServicePanel.cbxActionCompleted.text")); // NOI18N
        cbxActionCompleted.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbxActionCompleted.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cbxActionCompleted.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, applicationServiceBean, org.jdesktop.beansbinding.ELProperty.create("${actionCompleted}"), cbxActionCompleted, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout panelActionCompletedLayout = new javax.swing.GroupLayout(panelActionCompleted);
        panelActionCompleted.setLayout(panelActionCompletedLayout);
        panelActionCompletedLayout.setHorizontalGroup(
            panelActionCompletedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbxActionCompleted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblActionCompleted, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        panelActionCompletedLayout.setVerticalGroup(
            panelActionCompletedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionCompletedLayout.createSequentialGroup()
                .addComponent(lblActionCompleted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxActionCompleted)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        panelTop.add(panelActionCompleted);

        lblFieldA.setText(bundle.getString("ApplicationServicePanel.lblFieldA.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, applicationServiceBean, org.jdesktop.beansbinding.ELProperty.create("${reportTextOne}"), txtFieldA, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout panelALayout = new javax.swing.GroupLayout(panelA);
        panelA.setLayout(panelALayout);
        panelALayout.setHorizontalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFieldA, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(txtFieldA)
        );
        panelALayout.setVerticalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelALayout.createSequentialGroup()
                .addComponent(lblFieldA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        panelTop.add(panelA);

        lblFieldB.setText(bundle.getString("ApplicationServicePanel.lblFieldB.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, applicationServiceBean, org.jdesktop.beansbinding.ELProperty.create("${reportTextTwo}"), txtFieldB, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout panelBLayout = new javax.swing.GroupLayout(panelB);
        panelB.setLayout(panelBLayout);
        panelBLayout.setHorizontalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFieldB, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addComponent(txtFieldB)
        );
        panelBLayout.setVerticalGroup(
            panelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBLayout.createSequentialGroup()
                .addComponent(lblFieldB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelTop.add(panelB);

        lblNotes.setText(bundle.getString("ApplicationServicePanel.lblNotes.text")); // NOI18N

        txtNotes.setColumns(20);
        txtNotes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNotes.setLineWrap(true);
        txtNotes.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, applicationServiceBean, org.jdesktop.beansbinding.ELProperty.create("${actionNotes}"), txtNotes, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(txtNotes);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(documentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(groupPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionDateCalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionDateCalenderActionPerformed
        showCalendar(txtActionDate);
    }//GEN-LAST:event_btnActionDateCalenderActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.sola.clients.beans.application.ApplicationServiceBean applicationServiceBean;
    private javax.swing.JButton btnActionDateCalender;
    public javax.swing.JCheckBox cbxActionCompleted;
    private org.sola.clients.swing.desktop.source.DocumentsManagementExtPanel documentPanel;
    private javax.swing.Box.Filler filler1;
    private org.sola.clients.swing.ui.GroupPanel groupPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblActionCompleted;
    public javax.swing.JLabel lblActionDate;
    private javax.swing.JLabel lblFieldA;
    private javax.swing.JLabel lblFieldB;
    public javax.swing.JLabel lblNotes;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelActionCompleted;
    private javax.swing.JPanel panelActionDate;
    private javax.swing.JPanel panelB;
    private javax.swing.JPanel panelTop;
    private javax.swing.JFormattedTextField txtActionDate;
    private javax.swing.JTextField txtFieldA;
    private javax.swing.JTextField txtFieldB;
    private javax.swing.JTextArea txtNotes;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
